//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutData", ReplyAction="http://tempuri.org/IService1/PutDataResponse")]
        string PutData(
                    string UserID, 
                    string Interest, 
                    string TXNPrice, 
                    string TXNTax, 
                    string TXNAmount, 
                    string Type, 
                    string StartTime, 
                    string Duration, 
                    string NoOfMale, 
                    string NoOfFemale, 
                    string NoOfKid, 
                    string BabySeat, 
                    string Trailer, 
                    string Tandem, 
                    string auth_code, 
                    string transactionID, 
                    string First, 
                    string Last);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfServiceClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfServiceClient.ServiceReference1.IService1>, WcfServiceClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public string PutData(
                    string UserID, 
                    string Interest, 
                    string TXNPrice, 
                    string TXNTax, 
                    string TXNAmount, 
                    string Type, 
                    string StartTime, 
                    string Duration, 
                    string NoOfMale, 
                    string NoOfFemale, 
                    string NoOfKid, 
                    string BabySeat, 
                    string Trailer, 
                    string Tandem, 
                    string auth_code, 
                    string transactionID, 
                    string First, 
                    string Last) {
            return base.Channel.PutData(UserID, Interest, TXNPrice, TXNTax, TXNAmount, Type, StartTime, Duration, NoOfMale, NoOfFemale, NoOfKid, BabySeat, Trailer, Tandem, auth_code, transactionID, First, Last);
        }
    }
}
